### PR TITLE
Issue #131 fixed

### LINKED ISSUE #131: [Bug]: change the language of the Dialog in the confirmation boxes ("yes" and "no")
### 👉 Please confirm the following

- [x] I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.

### ❌ Current Behavior

The confirmation dialog when you exist the game are not translated because it is a bit complicated to translate them.

Image

### ✅ Expected Behavior

Translate these two buttons "yes" and "no".

### 🚩 Steps To Reproduce

1. Play the game
2. Press "escape"
3. Click on quit the game
4. And then you will a dialog opening with the two untranslated buttons

### 💻 Environment

```markdown
- OS: any
- Game version: 1.1.0
```

### ℹ️ Additional information

I found this info on the official documentation, so maybe try this : https://github.com/AlmasB/FXGL/wiki/Dialogs-(FXGL-11)#custom-dialog

### PR DESCRIPTION
**Pull request by Johann4002herti**
## 👉 Checklist

> Please make sure to check off the following before submitting:

- [x] I have reviewed my submission thoroughly.
- [x] I have tested my code (if submission is related to coding) and run the game before pushing (to make sure the project compile).
- [x] I have run the JUnit tests (if submission is related to coding).
- [x] I have read the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/dylan-power/dinosaur-exploder/blob/main/CONTRIBUTING.md).

## ✍ Description of the Pull Request

> Please concisely describe the changes you have made. 

- Issue #131: changed the Confirm-Dialog into a Custom-Dialog with Eventbased Buttons
- added translation for ShipSelection, LanguageSelection, GameOverScreen, and the SPACE-bar in the controls
- changed some german translation to a more "normal" german
- added ä,ö,ü into the font

## 🔗 Issue link

> Issue reference number and link goes here e.g. 'Fixes/Closes #131'.

- [x] This Pull Request fixes the issue : 'Closes #131'
- [ ] This Pull Request does not fix an issue. 

<br>

> Thanks for taking the time to fill out this Pull Request! ❤️ Thanks for contributing to this project 🦖

### CODE REVIEW

File: src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java [hunk 1]
```diff
@@ -126,12 +133,32 @@ public void initPhysics() {
...
+
+        /*getDialogService().showConfirmationBox(getLocalizationService().getLocalizedString("Game.2"), yes -> {
             if (yes) {
                 getGameController().startNewGame();
             } else {
                 getGameController().gotoMainMenu();
             }
-        });
-    }
+        });*/
```
Comment (jvondermarck) [inline src/main/java/com/dinosaur/dinosaurexploder/controller/DinosaurController.java:163]: Can you delete this comment ? It is dead code so useless

**Review by jvondermarck — APPROVED** [review]
Very great work, thank you so much for your contribution buddy !! 😍

**Comment by jvondermarck** [comment]
Can you pull the latest change from the branch `main` of this repository into your forked repository in your branch please ? I just updated a file and to be able to build the project before merging, we need the CI to work. @Johann4002herti 

> I updated this file : c48d1db7df66bc87755a5f3f5f3ae0dd4a0d1189

**Comment by jvondermarck** [comment]
I merged so that you don't have to take care of it, thanks for your contribution 🥳
